sudo: required
language: generic
dist: trusty

notifications:
  email:
    recipients:
      - spuetz@uos.de
    on_success: change
    on_failure: change

matrix:
  include:
    - name: "Lunar"
      env: ROS_DISTRO=lunar

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh